[package]
name = "day-3"
version = "0.1.0"
edition = "2021"
default-run = "day-3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
phf = { version = "0.11.1", features = ["macros"] }
